### ISSUE TITLE
Extend diff function to work with other types

### ISSUE THREAD

**Issue by OlegTheCat** [bryanjos/diff#1]
Current implementation allows comparisons of strings only: 

```
iex(10)> Diff.diff([1,2,3], [1,2,3])
** (FunctionClauseError) no function clause matching in String.Graphemes.graphemes/1
```

It would be great if this function could be applied for other collections, e.g. lists.
Probably, good solution will be to expose protocol Diffable (or so) with set of operations that are needed to perform a diff. This way, any user will be able to adapt library to his needs.

Let me know what you think about this.
Thanks.

**Comment by bryanjos** [comment]
I think that is a great idea! I might not get any time to get to it soon, but I'll try. If you want to make a PR for it I'll accept it as well.

**Comment by bryanjos** [comment]
Actually I guess I can just make the protocol and only implement it for strings. Let me see if I can do that today at least.

**Comment by bryanjos** [comment]
It's still rough, but I did add a Diff.Diffable protocol. It can be a lot better, but it gets the job done.

**Comment by OlegTheCat** [comment]
Looks great. Thanks a lot.
I think this issue can be closed now. If something goes wrong, I'll let you know or try to prepare PR myself.

Thanks again.

**Comment by bryanjos** [comment]
I've slept on it and I think I may change it to just accept and work on lists. From there it doesn't matter as long as what you give it can be turned into a list and can be converted from a list.

**Comment by bryanjos** [comment]
I updated `Diff.Diffable` to only have a to_list function to implement. I updated patch to take an optional `from_list_fn` that takes the patched list as input and allows you to turn it back into the type you need. This should give anyone who uses it a lot less to implement.

**Comment by OlegTheCat** [comment]
That's just awesome :+1: :+1: :+1: 
Thanks.
